
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    command: --default-authentication-plugin=mysql_native_password
###< doctrine/doctrine-bundle ###

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html:rw
      - ./var:/var/www/html/var:rw
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_SECRET=${APP_SECRET:-f7b83f19d2d0863e2d0e404a3e4680d3}
      - DATABASE_URL=mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-symfony}@database:3306/${MYSQL_DATABASE:-symfony}?serverVersion=${MYSQL_VERSION:-8.0}&charset=utf8mb4
    depends_on:
      - database
    command: php -S 0.0.0.0:8000 -t public

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
